apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
data:
{{ (.Files.Glob "todolist/*").AsConfig | indent 2 }}
{{ (.Files.Glob "todolist/app/*").AsConfig | indent 2 }}
{{ (.Files.Glob "todolist/app/templates/*").AsConfig | indent 2 }}




