apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: 1A2b3C.1
  replicaPassword: 1A2b3C.2


